# Generated by Django 4.2.13 on 2024-05-11 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_company_no_of_empolyees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="no_of_empolyees",
        ),
    ]
