# Generated by Django 4.2.13 on 2024-05-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightschedule",
            name="flight",
        ),
        migrations.AddField(
            model_name="flightschedule",
            name="flight_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight.flight",
            ),
        ),
        migrations.AlterField(
            model_name="flightsensordata",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight.flightschedule",
            ),
        ),
    ]
