# Generated by Django 4.2.13 on 2024-05-24 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("WS", "Wind Speed High"),
                            ("PP", "Precipitation High"),
                            ("TM", "Temperature High"),
                            ("VL", "Visibility Low"),
                            ("TB", "Turbulence High"),
                        ],
                        max_length=100,
                    ),
                ),
                ("impact", models.JSONField()),
                ("recommendation", models.JSONField()),
            ],
        ),
    ]
